### ISSUE TITLE
incomprehensible error. Paper 1.12.2

### ISSUE THREAD

**Issue by sergservis** [Ruinscraft/Panilla#72]
[20:39:54] [Server thread/ERROR]: Could not pass event BlockDispenseEvent to Panilla v1.6.3
java.lang.NoSuchMethodError: org.bukkit.block.ShulkerBox.getLootTable()Lorg/bukkit/loot/LootTable;
	at com.ruinscraft.panilla.bukkit.TileLootTableListener.onDispense(TileLootTableListener.java:55) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor169.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DispenseBehaviorItem.a(DispenseBehaviorItem.java:63) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DispenseBehaviorItem.b(DispenseBehaviorItem.java:26) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DispenseBehaviorItem.a(DispenseBehaviorItem.java:13) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.BlockDropper.dispense(BlockDropper.java:41) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.BlockDispenser.b(BlockDispenser.java:118) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:793) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:324) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:905) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by dextonanderson** [comment]
Hi,

Use the latest release I just put out `1.6.4`. It will solve this issue.
