### ISSUE TITLE
Spamming an error in the console

### ISSUE THREAD

**Issue by botinok224** [Ruinscraft/Panilla#79]
This spamming an error in the console
PaperSpigot 1.12.2
Panilla version downloaded from spigotmc (purchased)

Also, in some cases, the server may shut down due to strong spam errors

`[16:44:12 WARN]: java.io.IOException: Bad packet id 1000
[16:44:12 WARN]:        at net.minecraft.server.v1_12_R1.PacketDecoder.decode(SourceFile:37)
[16:44:12 WARN]:        at com.ruinscraft.panilla.craftbukkit.v1_12_R1.io.PlayerInjector$PanillaPacketDecoder.decode(PlayerInjector.java:46)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.lambda$sendRawPacketToServerServerSide$3(UserConnection.java:274)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.sendRawPacketToServerServerSide(UserConnection.java:280)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.sendRawPacketToServer(UserConnection.java:255)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.sendToServer(PacketWrapper.java:526)
[16:44:12 WARN]:        at nl.matsv.viabackwards.protocol.protocol1_11_1to1_12.packets.BlockItemPackets1_12$3$1.handle(BlockItemPackets1_12.java:141)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[16:44:12 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395)
[16:44:12 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
[16:44:12 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
[16:44:12 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:44:12 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[16:44:12 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:514)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:44:12 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[16:44:12 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:44:12 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[16:44:12 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[16:44:12 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[16:44:12 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[16:44:12 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[16:44:12 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
[16:44:12 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
[16:44:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:44:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by dextonanderson** [comment]
Hi,

Try this prerelease build and let me know if it solves your issue
[Panilla_1.6.5-pre1.zip](https://github.com/Ruinscraft/Panilla/files/6250399/Panilla_1.6.5-pre1.zip)

**Comment by botinok224** [comment]
It helped, the error was gone. Thanks
