### ISSUE TITLE
Not able to connect to the server anymore

### ISSUE THREAD

**Issue by Kronnox** [Ruinscraft/Panilla#98]
We just updated our servers to paper-1.17.1-233, including Panilla-1.7.2.
Since then no player is able to connect to the server. The connection is interrupted with the following error message:
```
[11:13:50 WARN]: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Object already disposed
[11:13:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:13:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:13:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[11:13:50 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:13:50 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:13:50 WARN]:        at Panilla-1.7.2.jar//com.ruinscraft.panilla.api.io.dplx.PacketInspectorDplx.write(PacketInspectorDplx.java:48)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[11:13:50 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[11:13:50 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[11:13:50 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:450)
[11:13:50 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[11:13:50 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[11:13:50 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[11:13:50 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[11:13:50 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[11:13:50 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[11:13:50 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:13:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[11:13:50 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
[11:13:50 WARN]:        at com.velocitypowered.natives.compression.LibdeflateVelocityCompressor.ensureNotDisposed(LibdeflateVelocityCompressor.java:65)
[11:13:50 WARN]:        at com.velocitypowered.natives.compression.LibdeflateVelocityCompressor.deflate(LibdeflateVelocityCompressor.java:46)
[11:13:50 WARN]:        at net.minecraft.network.PacketCompressor.encode(PacketCompressor.java:59)
[11:13:50 WARN]:        at net.minecraft.network.PacketCompressor.encode(PacketCompressor.java:8)
[11:13:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[11:13:50 WARN]:        ... 34 more
[11:13:50 WARN]: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Object already disposed
[11:13:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:13:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:13:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[11:13:50 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:13:50 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:13:50 WARN]:        at Panilla-1.7.2.jar//com.ruinscraft.panilla.api.io.dplx.PacketInspectorDplx.write(PacketInspectorDplx.java:48)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[11:13:50 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[11:13:50 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[11:13:50 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[11:13:50 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:450)
[11:13:50 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[11:13:50 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[11:13:50 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[11:13:50 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[11:13:50 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[11:13:50 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[11:13:50 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:13:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[11:13:50 WARN]: Caused by: java.lang.IllegalStateException: Object already disposed
[11:13:50 WARN]:        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
[11:13:50 WARN]:        at com.velocitypowered.natives.compression.LibdeflateVelocityCompressor.ensureNotDisposed(LibdeflateVelocityCompressor.java:65)
[11:13:50 WARN]:        at com.velocitypowered.natives.compression.LibdeflateVelocityCompressor.deflate(LibdeflateVelocityCompressor.java:46)
[11:13:50 WARN]:        at net.minecraft.network.PacketCompressor.encode(PacketCompressor.java:59)
[11:13:50 WARN]:        at net.minecraft.network.PacketCompressor.encode(PacketCompressor.java:8)
[11:13:50 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[11:13:50 WARN]:        ... 34 more
[11:13:50 INFO]: <player-name>[/<ip>] logged in with entity id 182 at ([plot2]146.91908525054095, 30.0, -157.4346778147137)
[11:13:50 INFO]: <player-name> lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Object already disposed
```
As soon as we disable Panilla, it works fine again.
Any idea what's causing this behaviour?

**Comment by Kronnox** [comment]
Duplicate of #92. Solution presented there.
